apiVersion: v1
kind: Service
metadata:
  name: vpro-service
  namespace: vpro
spec:
  type: NodePort
  selector:
    app: vpro-app
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000




    


